import {Component} from '@angular/core';

import {MenuController, Platform} from '@ionic/angular';
import {SplashScreen} from '@ionic-native/splash-screen/ngx';
import {StatusBar} from '@ionic-native/status-bar/ngx';
import {Router} from '@angular/router';

@Component({
    selector: 'app-root',
    templateUrl: 'app.component.html'
})
export class AppComponent {
    public appPages = [
        {
            title: 'Home',
            url: '/home',
            icon: 'home'
        }, {
            title: 'Infos',
            url: '/list',
            icon: 'information-circle-outline'
        }, {
            title: 'Kalender',
            url: '/home',
            icon: 'calendar'
        }, {
            title: 'Chat',
            url: '/home',
            icon: 'chatbubbles'
        }
    ];
    public optionPages = [
        {
            title: 'Einstellungen',
            url: '/home',
            icon: 'settings'
        }, {
            title: 'Hilfe und Feedback',
            url: '/home',
            icon: 'help-circle-outline'
        }
    ];
    public leaderPages = [
        {
            title: 'Planung',
            url: '/home',
            icon: 'bookmarks'
        }, {
            title: 'Gruppenliste',
            url: '/home',
            icon: 'list'
        }, {
            title: 'Nachrichten',
            url: '/home',
            icon: 'mail'
        }
    ];
    public accountPages = [
        {
            title: 'Konto vewalten',
            url: '/home',
            icon: 'person'
        }, {
            title: 'Abmelden',
            url: '/home',
            icon: 'log-out'
        }
    ];

    // true, when the accountPage is dropped right now
    public isDropped = false;

    constructor(
        private platform: Platform,
        private splashScreen: SplashScreen,
        private statusBar: StatusBar,
        private menuCtrl: MenuController,
        private router: Router
    ) {
        this.initializeApp();
    }

    /**
     * method generated by ionic
     */
    initializeApp() {
        this.platform.ready().then(() => {
            this.statusBar.styleDefault();
            this.splashScreen.hide();
        });
    }

    /**
     * @returns url from active router
     */
    getActiveUrl() {
        return this.router.url;
    }

    /**
     * toggle the account menu divs
     */
    public toggleAccountMenu() {
        document.getElementById('menu_default').classList.toggle('displayNone');
        document.getElementById('menu_account').classList.toggle('displayNone');
        this.isDropped = !this.isDropped;
    }

    /**
     * close the menu and toggle the account menu when dropped
     */
    public closeMenu() {
        this.menuCtrl.close();
        if (this.isDropped) {
            this.toggleAccountMenu();
        }
    }

    /**
     * use own close Method
     */
    public ionCloseMenu() {
        this.closeMenu();
    }
}
